//! `plant_harvest_runtime`.
//!
//! The declarations live in the `_<group>.zig` files beside this one and
//! are re-exported here, so `module.name` still resolves for every caller
//! and the grouping is a file layout choice rather than an API change.

const group_apply = @import("plant_harvest_runtime_apply.zig");
const group_harvest = @import("plant_harvest_runtime_harvest.zig");
const group_mass_helpers = @import("plant_harvest_runtime_mass_helpers.zig");
const group_misc = @import("plant_harvest_runtime_misc.zig");
const group_mortality = @import("plant_harvest_runtime_mortality.zig");
const group_source_order_exports = @import("plant_harvest_runtime_source_order_exports.zig");
const group_tests = @import("plant_harvest_runtime_tests.zig");
const group_types = @import("plant_harvest_runtime_types.zig");
const group_validation = @import("plant_harvest_runtime_validation.zig");

// apply
pub const applyForestSelfThinning = group_apply.applyForestSelfThinning;
pub const applyEvent = group_apply.applyEvent;
pub const applyAutomaticSelfSeedingHarvests = group_apply.applyAutomaticSelfSeedingHarvests;
pub const applyStartOfSeasonResidue = group_apply.applyStartOfSeasonResidue;
pub const applyWholePlantMortalityResidue = group_apply.applyWholePlantMortalityResidue;
pub const applyNaturalDeadBranchResidue = group_apply.applyNaturalDeadBranchResidue;
pub const applyAbovegroundTillage = group_apply.applyAbovegroundTillage;
pub const applyGrazingEvent = group_apply.applyGrazingEvent;
pub const applyRootSymbiontHarvest = group_apply.applyRootSymbiontHarvest;

// harvest
pub const harvest_product_component_count = group_harvest.harvest_product_component_count;
pub const prunedClumpingFactor = group_harvest.prunedClumpingFactor;
pub const cuttingHeightFromLeafAreaRemoval = group_harvest.cuttingHeightFromLeafAreaRemoval;
pub const harvestLitterToKinetics = group_harvest.harvestLitterToKinetics;
pub const publishPlantProducts = group_harvest.publishPlantProducts;
pub const sourceOrderBelowgroundHarvestComposition = group_harvest.sourceOrderBelowgroundHarvestComposition;

// mass helpers
pub const sumHarvestProductComponents = group_mass_helpers.sumHarvestProductComponents;
pub const scaleElementalMass = group_mass_helpers.scaleElementalMass;
pub const remainingShootPools = group_mass_helpers.remainingShootPools;
pub const uncombustedShootTotal = group_mass_helpers.uncombustedShootTotal;
pub const boundedCombustionFraction = group_mass_helpers.boundedCombustionFraction;
pub const subtractElementalMass = group_mass_helpers.subtractElementalMass;
pub const scaleSaltInventory = group_mass_helpers.scaleSaltInventory;
pub const subtractSaltInventory = group_mass_helpers.subtractSaltInventory;

// misc
pub const Context = group_misc.Context;
pub const PopulationAfterDisturbance = group_misc.PopulationAfterDisturbance;
pub const PostHarvestBinding = group_misc.PostHarvestBinding;

// mortality
pub const forestSelfThinningFraction = group_mortality.forestSelfThinningFraction;
pub const releaseDeadRootsToLitter = group_mortality.releaseDeadRootsToLitter;

// source order exports
pub const SourceOrderAbovegroundHarvestLitterInput = group_source_order_exports.SourceOrderAbovegroundHarvestLitterInput;
pub const SourceOrderAbovegroundHarvestLitterResult = group_source_order_exports.SourceOrderAbovegroundHarvestLitterResult;
pub const SourceOrderCharcoalCombustionResult = group_source_order_exports.SourceOrderCharcoalCombustionResult;
pub const SourceOrderColdSoilCombustionReset = group_source_order_exports.SourceOrderColdSoilCombustionReset;
pub const SourceOrderCombustionRates = group_source_order_exports.SourceOrderCombustionRates;
pub const SourceOrderCombustionSpecificRates = group_source_order_exports.SourceOrderCombustionSpecificRates;
pub const SourceOrderCompleteDeathBranchPools = group_source_order_exports.SourceOrderCompleteDeathBranchPools;
pub const SourceOrderCompleteDeathBranchState = group_source_order_exports.SourceOrderCompleteDeathBranchState;
pub const SourceOrderCompleteDeathRootInput = group_source_order_exports.SourceOrderCompleteDeathRootInput;
pub const SourceOrderCompleteDeathRootResetState = group_source_order_exports.SourceOrderCompleteDeathRootResetState;
pub const SourceOrderCompleteDeathShootInput = group_source_order_exports.SourceOrderCompleteDeathShootInput;
pub const SourceOrderCompleteDeathShootResult = group_source_order_exports.SourceOrderCompleteDeathShootResult;
pub const SourceOrderDeadBranchCanopyReset = group_source_order_exports.SourceOrderDeadBranchCanopyReset;
pub const SourceOrderDeadBranchLayerResetState = group_source_order_exports.SourceOrderDeadBranchLayerResetState;
pub const SourceOrderDeadBranchLitterInput = group_source_order_exports.SourceOrderDeadBranchLitterInput;
pub const SourceOrderDeadBranchLitterPools = group_source_order_exports.SourceOrderDeadBranchLitterPools;
pub const SourceOrderDeadBranchLitterResult = group_source_order_exports.SourceOrderDeadBranchLitterResult;
pub const SourceOrderDeadBranchNodeResetState = group_source_order_exports.SourceOrderDeadBranchNodeResetState;
pub const SourceOrderDeadBranchPhenologyState = group_source_order_exports.SourceOrderDeadBranchPhenologyState;
pub const SourceOrderDeadBranchResetInput = group_source_order_exports.SourceOrderDeadBranchResetInput;
pub const SourceOrderDeadBranchScalarResetState = group_source_order_exports.SourceOrderDeadBranchScalarResetState;
pub const SourceOrderDeadBranchStorageRecoveryInput = group_source_order_exports.SourceOrderDeadBranchStorageRecoveryInput;
pub const SourceOrderDeadBranchStorageRecoveryResult = group_source_order_exports.SourceOrderDeadBranchStorageRecoveryResult;
pub const SourceOrderDeadNoduleLayerPools = group_source_order_exports.SourceOrderDeadNoduleLayerPools;
pub const SourceOrderDeadNoduleLitterInput = group_source_order_exports.SourceOrderDeadNoduleLitterInput;
pub const SourceOrderDeadPerennialReseedResult = group_source_order_exports.SourceOrderDeadPerennialReseedResult;
pub const SourceOrderDeadRootAxisLayerState = group_source_order_exports.SourceOrderDeadRootAxisLayerState;
pub const SourceOrderDeadRootAxisPools = group_source_order_exports.SourceOrderDeadRootAxisPools;
pub const SourceOrderDeadRootDepthResetState = group_source_order_exports.SourceOrderDeadRootDepthResetState;
pub const SourceOrderDeadRootDomainAxisState = group_source_order_exports.SourceOrderDeadRootDomainAxisState;
pub const SourceOrderDeadRootDomainLayerState = group_source_order_exports.SourceOrderDeadRootDomainLayerState;
pub const SourceOrderDeadRootLayerLitter = group_source_order_exports.SourceOrderDeadRootLayerLitter;
pub const SourceOrderDeadRootLitterInput = group_source_order_exports.SourceOrderDeadRootLitterInput;
pub const SourceOrderDeadRootResetState = group_source_order_exports.SourceOrderDeadRootResetState;
pub const SourceOrderDisturbanceRemovalInput = group_source_order_exports.SourceOrderDisturbanceRemovalInput;
pub const SourceOrderDisturbanceRemovalResult = group_source_order_exports.SourceOrderDisturbanceRemovalResult;
pub const SourceOrderDormantSeedActivation = group_source_order_exports.SourceOrderDormantSeedActivation;
pub const SourceOrderDormantSeedBranch = group_source_order_exports.SourceOrderDormantSeedBranch;
pub const SourceOrderFireInventoryResult = group_source_order_exports.SourceOrderFireInventoryResult;
pub const SourceOrderFireLayerCarbon = group_source_order_exports.SourceOrderFireLayerCarbon;
pub const SourceOrderFirePlantInventory = group_source_order_exports.SourceOrderFirePlantInventory;
pub const SourceOrderFireShootCarbon = group_source_order_exports.SourceOrderFireShootCarbon;
pub const SourceOrderGrazingLitterLedgerState = group_source_order_exports.SourceOrderGrazingLitterLedgerState;
pub const SourceOrderGrazingLitterResult = group_source_order_exports.SourceOrderGrazingLitterResult;
pub const SourceOrderHarvestResidueInput = group_source_order_exports.SourceOrderHarvestResidueInput;
pub const SourceOrderLitterfallAccumulationInput = group_source_order_exports.SourceOrderLitterfallAccumulationInput;
pub const SourceOrderLitterfallAccumulationResult = group_source_order_exports.SourceOrderLitterfallAccumulationResult;
pub const SourceOrderNoCombustionReset = group_source_order_exports.SourceOrderNoCombustionReset;
pub const SourceOrderReseedDate = group_source_order_exports.SourceOrderReseedDate;
pub const SourceOrderRootAxisCombustionReset = group_source_order_exports.SourceOrderRootAxisCombustionReset;
pub const SourceOrderRootCombustionAxisState = group_source_order_exports.SourceOrderRootCombustionAxisState;
pub const SourceOrderRootCombustionDomainLoss = group_source_order_exports.SourceOrderRootCombustionDomainLoss;
pub const SourceOrderRootCombustionDomainState = group_source_order_exports.SourceOrderRootCombustionDomainState;
pub const SourceOrderRootCombustionFractions = group_source_order_exports.SourceOrderRootCombustionFractions;
pub const SourceOrderRootCombustionLayerTotals = group_source_order_exports.SourceOrderRootCombustionLayerTotals;
pub const SourceOrderRootCombustionPotentialRates = group_source_order_exports.SourceOrderRootCombustionPotentialRates;
pub const SourceOrderRootDomainCombustionResult = group_source_order_exports.SourceOrderRootDomainCombustionResult;
pub const SourceOrderRootGasInventory = group_source_order_exports.SourceOrderRootGasInventory;
pub const SourceOrderRootGasPhases = group_source_order_exports.SourceOrderRootGasPhases;
pub const SourceOrderRootNoduleCombustionResult = group_source_order_exports.SourceOrderRootNoduleCombustionResult;
pub const SourceOrderRootStorageCombustionInput = group_source_order_exports.SourceOrderRootStorageCombustionInput;
pub const SourceOrderRootStorageCombustionResult = group_source_order_exports.SourceOrderRootStorageCombustionResult;
pub const SourceOrderShootCombustionBranchPools = group_source_order_exports.SourceOrderShootCombustionBranchPools;
pub const SourceOrderShootCombustionBranchResult = group_source_order_exports.SourceOrderShootCombustionBranchResult;
pub const SourceOrderShootCombustionFractions = group_source_order_exports.SourceOrderShootCombustionFractions;
pub const SourceOrderShootCombustionNodeLayerState = group_source_order_exports.SourceOrderShootCombustionNodeLayerState;
pub const SourceOrderShootCombustionNodeState = group_source_order_exports.SourceOrderShootCombustionNodeState;
pub const SourceOrderShootCombustionResult = group_source_order_exports.SourceOrderShootCombustionResult;
pub const SourceOrderShootCombustionTotals = group_source_order_exports.SourceOrderShootCombustionTotals;
pub const SourceOrderShootSaltCombustionBranchResult = group_source_order_exports.SourceOrderShootSaltCombustionBranchResult;
pub const SourceOrderShootSaltInventory = group_source_order_exports.SourceOrderShootSaltInventory;
pub const SourceOrderSoilPlantExchangeInput = group_source_order_exports.SourceOrderSoilPlantExchangeInput;
pub const SourceOrderSoilPlantExchangeResult = group_source_order_exports.SourceOrderSoilPlantExchangeResult;
pub const SourceOrderStandingDeadCombustionComponent = group_source_order_exports.SourceOrderStandingDeadCombustionComponent;
pub const SourceOrderStandingDeadCombustionResult = group_source_order_exports.SourceOrderStandingDeadCombustionResult;
pub const SourceOrderStandingDeadGeometryInput = group_source_order_exports.SourceOrderStandingDeadGeometryInput;
pub const SourceOrderStandingDeadGeometryResult = group_source_order_exports.SourceOrderStandingDeadGeometryResult;
pub const SourceOrderStandingDeadHarvestInput = group_source_order_exports.SourceOrderStandingDeadHarvestInput;
pub const SourceOrderStandingDeadHarvestResult = group_source_order_exports.SourceOrderStandingDeadHarvestResult;
pub const SourceOrderTillageBranchLitterInput = group_source_order_exports.SourceOrderTillageBranchLitterInput;
pub const SourceOrderTillageBranchLitterResult = group_source_order_exports.SourceOrderTillageBranchLitterResult;
pub const SourceOrderTillageBranchPools = group_source_order_exports.SourceOrderTillageBranchPools;
pub const SourceOrderTillageBranchRetentionResult = group_source_order_exports.SourceOrderTillageBranchRetentionResult;
pub const SourceOrderTillageBranchScalarState = group_source_order_exports.SourceOrderTillageBranchScalarState;
pub const SourceOrderTillageLayerSampleState = group_source_order_exports.SourceOrderTillageLayerSampleState;
pub const SourceOrderTillageNodeState = group_source_order_exports.SourceOrderTillageNodeState;
pub const SourceOrderTillagePopulationInput = group_source_order_exports.SourceOrderTillagePopulationInput;
pub const SourceOrderTillagePopulationResult = group_source_order_exports.SourceOrderTillagePopulationResult;
pub const SourceOrderTillagePopulationState = group_source_order_exports.SourceOrderTillagePopulationState;
pub const SourceOrderTillageStandingDeadInput = group_source_order_exports.SourceOrderTillageStandingDeadInput;
pub const SourceOrderTillageStandingDeadResult = group_source_order_exports.SourceOrderTillageStandingDeadResult;
pub const SourceOrderTillageTerminationInput = group_source_order_exports.SourceOrderTillageTerminationInput;
pub const SourceOrderTillageTerminationResult = group_source_order_exports.SourceOrderTillageTerminationResult;
pub const SourceOrderTillageTerminationState = group_source_order_exports.SourceOrderTillageTerminationState;
pub const SourceOrderUncombustedBranchState = group_source_order_exports.SourceOrderUncombustedBranchState;
pub const SourceOrderWholePlantTerminationResult = group_source_order_exports.SourceOrderWholePlantTerminationResult;
pub const SourceOrderWholePlantTerminationState = group_source_order_exports.SourceOrderWholePlantTerminationState;
pub const sourceOrderAbovegroundDisturbanceIsEnabled = group_source_order_exports.sourceOrderAbovegroundDisturbanceIsEnabled;
pub const sourceOrderAbovegroundHarvestLitter = group_source_order_exports.sourceOrderAbovegroundHarvestLitter;
pub const sourceOrderAccumulateLitterfall = group_source_order_exports.sourceOrderAccumulateLitterfall;
pub const sourceOrderAccumulateSoilPlantExchange = group_source_order_exports.sourceOrderAccumulateSoilPlantExchange;
pub const sourceOrderAggregateFireCarbonInventory = group_source_order_exports.sourceOrderAggregateFireCarbonInventory;
pub const sourceOrderApplyRootDomainCombustion = group_source_order_exports.sourceOrderApplyRootDomainCombustion;
pub const sourceOrderApplyUncombustedShootState = group_source_order_exports.sourceOrderApplyUncombustedShootState;
pub const sourceOrderCharcoalCombustion = group_source_order_exports.sourceOrderCharcoalCombustion;
pub const sourceOrderCombustionRates = group_source_order_exports.sourceOrderCombustionRates;
pub const sourceOrderCompleteDeathRootLitterfall = group_source_order_exports.sourceOrderCompleteDeathRootLitterfall;
pub const sourceOrderCompleteDeathShootLitterfall = group_source_order_exports.sourceOrderCompleteDeathShootLitterfall;
pub const sourceOrderCuttingHeightFromLeafAreaRemoval = group_source_order_exports.sourceOrderCuttingHeightFromLeafAreaRemoval;
pub const sourceOrderDeadBranchLitterfall = group_source_order_exports.sourceOrderDeadBranchLitterfall;
pub const sourceOrderDeadBranchStorageRecovery = group_source_order_exports.sourceOrderDeadBranchStorageRecovery;
pub const sourceOrderDeadNoduleLitterfall = group_source_order_exports.sourceOrderDeadNoduleLitterfall;
pub const sourceOrderDeadRootLitterfall = group_source_order_exports.sourceOrderDeadRootLitterfall;
pub const sourceOrderDormantSeedActivation = group_source_order_exports.sourceOrderDormantSeedActivation;
pub const sourceOrderForestSelfThinningIsEnabled = group_source_order_exports.sourceOrderForestSelfThinningIsEnabled;
pub const sourceOrderGrazingLitterLedgers = group_source_order_exports.sourceOrderGrazingLitterLedgers;
pub const sourceOrderHarvestResidueRouting = group_source_order_exports.sourceOrderHarvestResidueRouting;
pub const sourceOrderHourlyDisturbanceReset = group_source_order_exports.sourceOrderHourlyDisturbanceReset;
pub const sourceOrderPopulationAfterDisturbance = group_source_order_exports.sourceOrderPopulationAfterDisturbance;
pub const sourceOrderPopulationScaledNumericalThresholds = group_source_order_exports.sourceOrderPopulationScaledNumericalThresholds;
pub const sourceOrderReleaseDeadRootGases = group_source_order_exports.sourceOrderReleaseDeadRootGases;
pub const sourceOrderResetColdSoilCombustion = group_source_order_exports.sourceOrderResetColdSoilCombustion;
pub const sourceOrderResetCompleteDeathBranches = group_source_order_exports.sourceOrderResetCompleteDeathBranches;
pub const sourceOrderResetCompleteDeathRoots = group_source_order_exports.sourceOrderResetCompleteDeathRoots;
pub const sourceOrderResetDeadBranchCanopy = group_source_order_exports.sourceOrderResetDeadBranchCanopy;
pub const sourceOrderResetDeadBranchPhenology = group_source_order_exports.sourceOrderResetDeadBranchPhenology;
pub const sourceOrderResetDeadRootDepth = group_source_order_exports.sourceOrderResetDeadRootDepth;
pub const sourceOrderResetDeadRootState = group_source_order_exports.sourceOrderResetDeadRootState;
pub const sourceOrderResetNoCombustion = group_source_order_exports.sourceOrderResetNoCombustion;
pub const sourceOrderRetainTillageBranchState = group_source_order_exports.sourceOrderRetainTillageBranchState;
pub const sourceOrderRootNoduleCombustion = group_source_order_exports.sourceOrderRootNoduleCombustion;
pub const sourceOrderRootStorageCombustion = group_source_order_exports.sourceOrderRootStorageCombustion;
pub const sourceOrderScheduleDeadPerennialReseed = group_source_order_exports.sourceOrderScheduleDeadPerennialReseed;
pub const sourceOrderShootCombustionFractions = group_source_order_exports.sourceOrderShootCombustionFractions;
pub const sourceOrderShootCombustionLosses = group_source_order_exports.sourceOrderShootCombustionLosses;
pub const sourceOrderShootSaltCombustion = group_source_order_exports.sourceOrderShootSaltCombustion;
pub const sourceOrderStandingDeadCombustion = group_source_order_exports.sourceOrderStandingDeadCombustion;
pub const sourceOrderStandingDeadGeometry = group_source_order_exports.sourceOrderStandingDeadGeometry;
pub const sourceOrderStandingDeadHarvest = group_source_order_exports.sourceOrderStandingDeadHarvest;
pub const sourceOrderTillageBranchLitter = group_source_order_exports.sourceOrderTillageBranchLitter;
pub const sourceOrderTillagePopulationReduction = group_source_order_exports.sourceOrderTillagePopulationReduction;
pub const sourceOrderTillageStandingDead = group_source_order_exports.sourceOrderTillageStandingDead;
pub const sourceOrderTillageTermination = group_source_order_exports.sourceOrderTillageTermination;
pub const sourceOrderTotalDisturbanceRemoval = group_source_order_exports.sourceOrderTotalDisturbanceRemoval;
pub const sourceOrderWholePlantTermination = group_source_order_exports.sourceOrderWholePlantTermination;

// tests

// types
pub const ScienceParameters = group_types.ScienceParameters;
pub const ProductLedger = group_types.ProductLedger;
pub const HourlyDisturbanceReset = group_types.HourlyDisturbanceReset;
pub const TillageElementComposition = group_types.TillageElementComposition;
pub const BelowgroundHarvestComposition = group_types.BelowgroundHarvestComposition;
pub const source_order_standing_dead_component_count = group_types.source_order_standing_dead_component_count;
pub const PopulationScaledNumericalThresholds = group_types.PopulationScaledNumericalThresholds;

// validation
pub const validateTillageComposition = group_validation.validateTillageComposition;
pub const validateTillageSlice = group_validation.validateTillageSlice;
pub const validateSourceOrderRootMass = group_validation.validateSourceOrderRootMass;
pub const validateDeadRootResetMass = group_validation.validateDeadRootResetMass;
pub const validateDeadNoduleMass = group_validation.validateDeadNoduleMass;
pub const validateDeadRootDepthMass = group_validation.validateDeadRootDepthMass;
pub const validateCompleteDeathMass = group_validation.validateCompleteDeathMass;
pub const validateCompleteDeathResultMass = group_validation.validateCompleteDeathResultMass;
pub const validateCombustionNode = group_validation.validateCombustionNode;

test {
    // A bare reference is what makes `zig build test` reach a file.
    _ = @import("plant_harvest_runtime_tests.zig");
    _ = @import("../validation/plant_harvest_runtime_test.zig");
}
