C     GENERATED BY ecosys-audit/scripts/kernelgen.py -- DO NOT EDIT BY HAND.
C     Matched-state oracle for STOMATE (f77src/stomate.f:2-673).
C     Reads pre-call state, calls the routine once, writes post-call state.
C     Layout: 74 items, 36994008 bytes, see the JSON manifest.
      PROGRAM KERNEL
      include "parameters.h"
      include "blkc.h"
      include "blk1cp.h"
      include "blk1g.h"
      include "blk1n.h"
      include "blk1p.h"
      include "blk2a.h"
      include "blk3.h"
      include "blk5.h"
      include "blk8a.h"
      include "blk8b.h"
      include "blk9a.h"
      include "blk9b.h"
      include "blk9c.h"
      include "blk1u.h"
      INTEGER I,J,NFZ,NZ,NY,NX
      CHARACTER*32 CARG
      INTEGER NARGS, IARG
      INTEGER IOS
      I=-9999
      J=-9999
      NFZ=-9999
      NZ=-9999
      NY=-9999
      NX=-9999
      NARGS=COMMAND_ARGUMENT_COUNT()
      IF(NARGS.GE.6)THEN
      CALL GET_COMMAND_ARGUMENT(1,CARG)
      READ(CARG,*,IOSTAT=IOS) I
      IF(IOS.NE.0)THEN
      WRITE(*,*)'kernelgen: bad argv integer for I',CARG
      STOP 2
      ENDIF
      CALL GET_COMMAND_ARGUMENT(2,CARG)
      READ(CARG,*,IOSTAT=IOS) J
      IF(IOS.NE.0)THEN
      WRITE(*,*)'kernelgen: bad argv integer for J',CARG
      STOP 2
      ENDIF
      CALL GET_COMMAND_ARGUMENT(3,CARG)
      READ(CARG,*,IOSTAT=IOS) NFZ
      IF(IOS.NE.0)THEN
      WRITE(*,*)'kernelgen: bad argv integer for NFZ',CARG
      STOP 2
      ENDIF
      CALL GET_COMMAND_ARGUMENT(4,CARG)
      READ(CARG,*,IOSTAT=IOS) NZ
      IF(IOS.NE.0)THEN
      WRITE(*,*)'kernelgen: bad argv integer for NZ',CARG
      STOP 2
      ENDIF
      CALL GET_COMMAND_ARGUMENT(5,CARG)
      READ(CARG,*,IOSTAT=IOS) NY
      IF(IOS.NE.0)THEN
      WRITE(*,*)'kernelgen: bad argv integer for NY',CARG
      STOP 2
      ENDIF
      CALL GET_COMMAND_ARGUMENT(6,CARG)
      READ(CARG,*,IOSTAT=IOS) NX
      IF(IOS.NE.0)THEN
      WRITE(*,*)'kernelgen: bad argv integer for NX',CARG
      STOP 2
      ENDIF
      ELSE
      OPEN(82,FILE='kernel_stomate.args',FORM='UNFORMATTED',
     2ACCESS='STREAM',STATUS='OLD',IOSTAT=IOS)
      IF(IOS.EQ.0)THEN
      READ(82) I
      READ(82) J
      READ(82) NFZ
      READ(82) NZ
      READ(82) NY
      READ(82) NX
      CLOSE(82)
      ELSE
      WRITE(*,*)'kernelgen: missing required arguments'
      WRITE(*,*)'supply 6 args: I,J,NFZ,NZ,NY,NX'
      STOP 2
      ENDIF
      ENDIF
      IF(I.LT.1.OR.I.GT.366)THEN
      WRITE(*,*)'kernelgen: argument I out of bounds [1,366]:',I
      STOP 2
      ENDIF
      IF(J.LT.1.OR.J.GT.24)THEN
      WRITE(*,*)'kernelgen: argument J out of bounds [1,24]:',J
      STOP 2
      ENDIF
      IF(NFZ.LT.1.OR.NFZ.GT.100)THEN
      WRITE(*,*)'kernelgen: argument NFZ out of bounds [1,100]:',NFZ
      STOP 2
      ENDIF
      IF(NZ.LT.1.OR.NZ.GT.JP)THEN
      WRITE(*,*)'kernelgen: argument NZ out of bounds [1,JP]:',NZ
      STOP 2
      ENDIF
      IF(NY.LT.1.OR.NY.GT.JY)THEN
      WRITE(*,*)'kernelgen: argument NY out of bounds [1,JY]:',NY
      STOP 2
      ENDIF
      IF(NX.LT.1.OR.NX.GT.JX)THEN
      WRITE(*,*)'kernelgen: argument NX out of bounds [1,JX]:',NX
      STOP 2
      ENDIF
      OPEN(81,FILE='kernel_stomate.in',FORM='UNFORMATTED',
     2ACCESS='STREAM',STATUS='OLD',IOSTAT=IOS)
      IF(IOS.NE.0)THEN
      WRITE(*,*)'kernelgen: cannot open input snapshot',IOS
      STOP 2
      ENDIF
      READ(81) WGLF
      READ(81) ARLF
      READ(81) ARLFL
      READ(81) WSLF
      READ(81) CCPOLB
      READ(81) O2I
      READ(81) CO2I
      READ(81) DCO2
      READ(81) CO2L
      READ(81) O2L
      READ(81) SCO2
      READ(81) SO2
      READ(81) XKCO2L
      READ(81) XKCO2O
      READ(81) TCC
      READ(81) TKC
      READ(81) HEAT
      READ(81) PARDIF
      READ(81) PAR
      READ(81) SURFX
      READ(81) VCGRO
      READ(81) VGRO
      READ(81) COMPL
      READ(81) ETGRO
      READ(81) CBXN
      READ(81) FMOL
      READ(81) FRADP
      READ(81) CO2B
      READ(81) VCGR4
      READ(81) VGRO4
      READ(81) ETGR4
      READ(81) CBXN4
      READ(81) CPOOL4
      READ(81) ARLFP
      READ(81) FDBK
      READ(81) FDBK4
      READ(81) FDBKX
      READ(81) CZPOLB
      READ(81) CPPOLB
      READ(81) RSMN
      READ(81) SSIN
      READ(81) CO2Q
      READ(81) FLG4
      READ(81) VRNS
      READ(81) VRNF
      READ(81) ATRP
      READ(81) NBR
      READ(81) IDTHB
      READ(81) TAU0
      READ(81) TAUS
      READ(81) NU
      READ(81) AREA
      READ(81) VCMX
      READ(81) VOMX
      READ(81) VCMX4
      READ(81) XKCO2
      READ(81) XKO2
      READ(81) XKCO24
      READ(81) RUBP
      READ(81) PEPC
      READ(81) ETMX
      READ(81) CHL
      READ(81) CHL4
      READ(81) FCO2
      READ(81) VRNL
      READ(81) RSMH
      READ(81) VRNX
      READ(81) OFFST
      READ(81) ICTYP
      READ(81) ISTYP
      READ(81) IWTYP
      READ(81) IBTYP
      READ(81) ZERO
      READ(81) ZEROP
      CLOSE(81)
      CALL STOMATE(I,J,NFZ,NZ,NY,NX)
      OPEN(83,FILE='kernel_stomate.out',FORM='UNFORMATTED',
     2ACCESS='STREAM',STATUS='REPLACE',IOSTAT=IOS)
      IF(IOS.NE.0)THEN
      WRITE(*,*)'kernelgen: cannot open output snapshot',IOS
      STOP 2
      ENDIF
      WRITE(83) WGLF
      WRITE(83) ARLF
      WRITE(83) ARLFL
      WRITE(83) WSLF
      WRITE(83) CCPOLB
      WRITE(83) O2I
      WRITE(83) CO2I
      WRITE(83) DCO2
      WRITE(83) CO2L
      WRITE(83) O2L
      WRITE(83) SCO2
      WRITE(83) SO2
      WRITE(83) XKCO2L
      WRITE(83) XKCO2O
      WRITE(83) TCC
      WRITE(83) TKC
      WRITE(83) HEAT
      WRITE(83) PARDIF
      WRITE(83) PAR
      WRITE(83) SURFX
      WRITE(83) VCGRO
      WRITE(83) VGRO
      WRITE(83) COMPL
      WRITE(83) ETGRO
      WRITE(83) CBXN
      WRITE(83) FMOL
      WRITE(83) FRADP
      WRITE(83) CO2B
      WRITE(83) VCGR4
      WRITE(83) VGRO4
      WRITE(83) ETGR4
      WRITE(83) CBXN4
      WRITE(83) CPOOL4
      WRITE(83) ARLFP
      WRITE(83) FDBK
      WRITE(83) FDBK4
      WRITE(83) FDBKX
      WRITE(83) CZPOLB
      WRITE(83) CPPOLB
      WRITE(83) RSMN
      WRITE(83) SSIN
      WRITE(83) CO2Q
      WRITE(83) FLG4
      WRITE(83) VRNS
      WRITE(83) VRNF
      WRITE(83) ATRP
      WRITE(83) NBR
      WRITE(83) IDTHB
      WRITE(83) TAU0
      WRITE(83) TAUS
      WRITE(83) NU
      WRITE(83) AREA
      WRITE(83) VCMX
      WRITE(83) VOMX
      WRITE(83) VCMX4
      WRITE(83) XKCO2
      WRITE(83) XKO2
      WRITE(83) XKCO24
      WRITE(83) RUBP
      WRITE(83) PEPC
      WRITE(83) ETMX
      WRITE(83) CHL
      WRITE(83) CHL4
      WRITE(83) FCO2
      WRITE(83) VRNL
      WRITE(83) RSMH
      WRITE(83) VRNX
      WRITE(83) OFFST
      WRITE(83) ICTYP
      WRITE(83) ISTYP
      WRITE(83) IWTYP
      WRITE(83) IBTYP
      WRITE(83) ZERO
      WRITE(83) ZEROP
      CLOSE(83)
      WRITE(*,*)'kernelgen: ok'
      END
