# GENERATED BY ecosys-audit/scripts/kernelgen.py -- DO NOT EDIT BY HAND.
# Builds the matched-state oracle for STOMATE. Run from the project root.
# The driver and the legacy unit are compiled separately on purpose: the driver needs
# ACCESS='STREAM' (Fortran 2003) and the legacy unit needs -std=legacy. Both use the
# same -fdefault-real-8/-fdefault-double-8 precision contract recorded in the manifest.
$ErrorActionPreference = 'Stop'
$out = if ($args.Count -ge 1) { $args[0] } else { Join-Path $PWD 'audit/tests/kernels/build' }
New-Item -ItemType Directory -Path $out -Force | Out-Null


& gfortran -c -ffixed-form -ffixed-line-length-72 -fdefault-real-8 -fdefault-double-8 -fcheck=bounds -I f77src `
  -o (Join-Path $out 'kernel_stomate.o') 'audit/tests/kernels/kernel_stomate.f'
if ($LASTEXITCODE -ne 0) { throw "driver compile failed" }
& gfortran -c -ffixed-form -ffixed-line-length-72 -fdefault-real-8 -fdefault-double-8 -std=legacy -fallow-argument-mismatch -fcheck=bounds -I f77src `
  -o (Join-Path $out 'stomate.o') 'f77src/stomate.f'
if ($LASTEXITCODE -ne 0) { throw "legacy unit compile failed" }
& gfortran -o (Join-Path $out 'kernel_stomate.exe') `
  (Join-Path $out 'kernel_stomate.o') (Join-Path $out 'stomate.o')
if ($LASTEXITCODE -ne 0) { throw "link failed" }
Write-Output "built $(Join-Path $out 'kernel_stomate.exe')"
Write-Output "run it in a directory holding kernel_stomate.in (36994008 bytes); it writes kernel_stomate.out"
