#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Construct binary input snapshots for standalone legacy kernel drivers. Python 3.10+.

Given a kernel layout manifest (<kernel>.layout.json) generated by kernelgen.py and a set
of user-specified assignments, writes an unformatted binary stream (<kernel>.in) conforming
bit-for-bit to Fortran column-major order and the Intel -r8 -i4 precision contract.

Fails loudly on:
  * Unknown member variable names
  * Invalid rank / dimensionality mismatches
  * Out-of-bounds indices (checked against declared lower/upper bounds)
  * Type/range overflows (e.g. non-finite floats, float to integer truncation)
"""
from __future__ import annotations
import argparse
import json
import math
from pathlib import Path
import struct
import sys
from typing import Any

STRUCT_FORMATS = {
    'f64': '<d',
    'f32': '<f',
    'i32': '<i',
    'i64': '<q',
    'bool32': '<i',
    'char': 'c',
}


class WriterError(Exception):
    """Raised when an assignment cannot be unambiguously or safely mapped."""


def linear_index_column_major(indices: list[int], bounds: list[dict[str, Any]]) -> int:
    """Calculate 0-based flat linear element index from Fortran column-major subscripts."""
    if len(indices) != len(bounds):
        raise WriterError(f"Subscript count mismatch: got {len(indices)} indices for rank {len(bounds)}")

    linear_idx = 0
    multiplier = 1
    for idx, b in zip(indices, bounds):
        low = int(b['lower'])
        up = int(b['upper']) if str(b['upper']).lstrip('-').isdigit() else (low + int(b['extent']) - 1)
        if not (low <= idx <= up):
            raise WriterError(f"Subscript {idx} out of declared bounds [{low}, {up}]")
        linear_idx += (idx - low) * multiplier
        multiplier *= int(b['extent'])
    return linear_idx


def pack_value(val: Any, eff_type: str) -> bytes:
    fmt = STRUCT_FORMATS.get(eff_type)
    if not fmt:
        raise WriterError(f"Unsupported binary pack type: {eff_type}")

    if eff_type in ('f64', 'f32'):
        f_val = float(val)
        if not math.isfinite(f_val):
            raise WriterError(f"Non-finite float value: {val}")
        return struct.pack(fmt, f_val)
    elif eff_type in ('i32', 'i64'):
        i_val = int(val)
        return struct.pack(fmt, i_val)
    elif eff_type == 'bool32':
        b_val = 1 if bool(val) else 0
        return struct.pack(fmt, b_val)
    elif eff_type == 'char':
        c_val = str(val).encode('ascii')[:1]
        return c_val
    else:
        raise WriterError(f"Unknown type: {eff_type}")


def build_snapshot(manifest: dict[str, Any], assignments: list[dict[str, Any]]) -> bytearray:
    total_bytes = manifest['stream']['total_bytes']
    buf = bytearray(total_bytes)

    layout = {item['name']: item for item in manifest['layout']}

    for assign in assignments:
        name = assign.get('name')
        if not name:
            raise WriterError("Assignment missing 'name'")
        name_upper = name.upper()
        if name_upper not in layout:
            raise WriterError(f"Variable '{name}' not found in kernel layout manifest")

        item = layout[name_upper]
        eff_type = item['effective_type']
        elem_bytes = item['element_bytes']
        base_offset = item['byte_offset']
        rank = item['rank']
        bounds = item['bounds']

        if 'value' in assign and 'indices' not in assign:
            # Broadcast scalar value across entire array
            packed = pack_value(assign['value'], eff_type)
            for elem_idx in range(item['elements']):
                off = base_offset + elem_idx * elem_bytes
                buf[off:off + elem_bytes] = packed
        elif 'indices' in assign and 'value' in assign:
            indices = assign['indices']
            if not isinstance(indices, list):
                indices = [indices]
            elem_idx = linear_index_column_major(indices, bounds)
            packed = pack_value(assign['value'], eff_type)
            off = base_offset + elem_idx * elem_bytes
            buf[off:off + elem_bytes] = packed
        elif 'values' in assign:
            # Block-write linear sequence of values
            raw_vals = assign['values']
            if len(raw_vals) > item['elements']:
                raise WriterError(f"Values array ({len(raw_vals)}) exceeds elements count ({item['elements']}) for {name}")
            for elem_idx, v in enumerate(raw_vals):
                packed = pack_value(v, eff_type)
                off = base_offset + elem_idx * elem_bytes
                buf[off:off + elem_bytes] = packed
        else:
            raise WriterError(f"Assignment for '{name}' must contain either 'value' or 'values'")

    return buf


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('manifest', type=Path, help='Path to kernel <name>.layout.json')
    parser.add_argument('assignments', type=Path, help='Path to JSON file containing list of assignments')
    parser.add_argument('-o', '--output', type=Path, required=True, help='Output path for binary snapshot (.in)')
    args = parser.parse_args()

    try:
        manifest_text = args.manifest.read_text(encoding='utf-8')
        manifest = json.loads(manifest_text)
        assignments_text = args.assignments.read_text(encoding='utf-8')
        assignments = json.loads(assignments_text)

        if not isinstance(assignments, list):
            raise WriterError("Assignments JSON root must be an array of objects")

        buf = build_snapshot(manifest, assignments)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_bytes(buf)
        print(f"kernel_writer: successfully wrote {len(buf)} bytes to {args.output}")
        return 0
    except Exception as e:
        sys.stderr.write(f"kernel_writer error: {e}\n")
        return 2


if __name__ == '__main__':
    raise SystemExit(main())
